"""empty message

Revision ID: 10a9a76125ac
Revises: 
Create Date: 2017-04-24 06:56:00.638615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10a9a76125ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'pub_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('pub_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
