"""empty message

Revision ID: ca140c4ac711
Revises: 6b47ddde7d68
Create Date: 2017-04-28 14:10:31.594909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca140c4ac711'
down_revision = '6b47ddde7d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('username', sa.String(255), nullable=True),
    sa.Column('password', sa.String(255), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
